[package]
name = "ws-stream"
version = "0.1.0"
edition = "2021"

[dependencies]
fred.workspace = true
futures-util.workspace = true
serde.workspace = true
serde_json.workspace = true
tokio.workspace = true
tokio-tungstenite.workspace = true
uuid.workspace = true

redis = { path = "../redis" }
