[package]
name = "ws-stream"
version = "0.1.0"
edition = "2021"

[dependencies]
fred = "10.1.0"
futures-util = "0.3.31"
serde = "1.0.228"
serde_json = "1.0.145"
tokio = "1.47.1"
tokio-tungstenite = "0.28.0"
uuid = "1.18.1"

redis = { path = "../redis" }