[package]
name = "sqlx_postgres"
version = "0.1.0"
edition = "2021"

[dependencies]
sqlx = { version = "0.8.6", features = ["runtime-tokio-rustls", "postgres", "chrono", "uuid", "macros"] }
tokio = "1.47.1"
serde = { version = "1.0", features = ["derive"] }
