/**
 * Data structure for How It Works section
 * Contains all steps, subheadings, and substeps with their descriptions
 */

import type { Step, Substep } from "@/types/howItWorks";

export type { Step, Substep };

export const HOW_IT_WORKS_STEPS: Step[] = [
  {
    title: "Join the Movement",
    subheadings: [
      "Fans: Create Your Account",
      "Creators: Get Onboard and Verified",
    ],
    substeps: [
      {
        title: "Get Started with Ease: Fan Sign-Up and Security Setup",
        description:
          "Fans create an account with a quick sign-up process, providing an email and password, then verify their identity and enable two-factor authentication (2FA) for enhanced security.",
        image: "/fans-signup.png",
      },
      {
        title: "Creators: Build Your Profile and Get Verified",
        description:
          "Creators onboard by registering and submitting a detailed profile, including a bio, links to their social media (e.g., YouTube, TikTok, Instagram), and a compelling pitch about their brand. The platform reviews and approves creators to ensure authenticity, setting the stage for their token launch.",
        image: "/fans-signup.png",
      },
    ],
  },
  {
    title: "Fund Your Account",
    subheadings: [
      "Fans: Deposit Cryptocurrency Securely",
      "Creators: Prepare for Token Launch",
    ],
    substeps: [
      {
        title: "Fans: Seamless Cryptocurrency Deposits",
        description:
          "Fans request a unique deposit address for cryptocurrencies like USDC, seamlessly generated by the platform. They transfer funds from their external blockchain wallet, and after blockchain confirmation, the funds are credited to a universal balance, ready for trading.",
        image: "/fans-signup.png",
      },
      {
        title: "Creators: Ready to Launch Without Upfront Funding",
        description:
          "Creators don't need to fund an account upfront; they prepare for their token launch and will receive proceeds directly from fan investments.",
        image: "/fans-signup.png",
      },
    ],
  },
  {
    title: "Launch Your Token",
    subheadings: ["Creators: Launch Your ICO", "Creators: Promote Your Token"],
    substeps: [
      {
        title: "Creators: Launch Your Unique Token Through ICO",
        description:
          "Approved creators launch their single, unique token tied to their personal brand through an Initial Coin Offering (ICO). They set the token's supply and price, tailoring the offering to reflect their vision and funding goals.",
        image: "/fans-signup.png",
      },
      {
        title: "Creators: Spark Excitement and Drive Participation",
        description:
          "Creators promote their ICO to their fanbase, sharing their story and plans to spark excitement and drive participation.",
        image: "/fans-signup.png",
      },
    ],
  },
  {
    title: "Invest in Creators",
    subheadings: ["Fans: Buy Tokens During ICO", "Fans: Build Your Portfolio"],
    substeps: [
      {
        title: "Fans: Secure Your Stake in Creator Success",
        description:
          "Fans use their universal balance to buy creator tokens during the ICO, securing a stake in their favorite creators' success. The platform makes it easy to participate with a few clicks, ensuring a smooth and engaging experience.",
        image: "/fans-signup.png",
      },
      {
        title: "Fans: Expand Your Creator Portfolio",
        description:
          "After the ICO, fans can continue to purchase tokens in the secondary marketplace, building a portfolio of creators they believe in.",
        image: "/fans-signup.png",
      },
    ],
  },
  {
    title: "Trade and Hold",
    subheadings: ["Fans: Trade Smartly", "Creators: Engage Your Community"],
    substeps: [
      {
        title: "Fans: Master the Marketplace",
        description:
          "Fans actively trade creator tokens in the platform's dynamic marketplace, buying low or selling high based on market trends and creator popularity. They can also hold tokens long-term, betting on a creator's growing influence to increase token value.",
        image: "/fans-signup.png",
      },
      {
        title: "Creators: Boost Your Token's Value",
        description:
          "Creators keep fans engaged by sharing regular updates, exclusive content, or special perks (like VIP events or merchandise), boosting their token's appeal and driving demand.",
        image: "/fans-signup.png",
      },
    ],
  },
  {
    title: "Cash Out or Grow",
    subheadings: ["Fans: Withdraw Earnings", "Creators: Fund Your Vision"],
    substeps: [
      {
        title: "Fans: Secure Withdrawals to Your Wallet",
        description:
          "Fans can withdraw their earnings or unused funds to any external blockchain wallet with a secure, straightforward process, receiving confirmation once the transfer is complete.",
        image: "/fans-signup.png",
      },
      {
        title: "Creators: Turn Token Sales Into Creative Fuel",
        description:
          "Creators withdraw proceeds from their token sales to fund their creative projects, such as producing new content or launching products, while rewarding token-holding fans with exclusive experiences or benefits.",
        image: "/fans-signup.png",
      },
    ],
  },
  {
    title: "Grow the Community",
    subheadings: [
      "Fans: Share and Discover",
      "Creators: Expand Your Influence",
    ],
    substeps: [
      {
        title: "Fans and Creators: Build a Vibrant Global Community",
        description:
          "Fans and creators alike contribute to a vibrant, global community. Fans share their investment successes and discover new creators, while creators leverage their token's popularity to expand their reach and influence.",
        image: "/fans-signup.png",
      },
      {
        title: "Platform Events: Keep the Community Buzzing",
        description:
          "The platform hosts events, leaderboards, or campaigns to keep the community buzzing, encouraging fans to rally behind creators and creators to innovate for their token holders.",
        image: "/fans-signup.png",
      },
    ],
  },
];
